#ABRIR ARCHIVO
animals = open("animals.txt","r+") #a+ = ABRIR PARA LEER Y AGREGAR
#HAY OTROS MODOS (SEGUNDO PARAMETRO):
#r = ABRE PARA LEER (DEFAULT, NO HACE FALTA ESCRIBIRLO)
#w = ABRE PARA ESCRIBIR Y TRUNCAR (BORRA TODO LO QUE HAY EN EL ARCHIVO)
#r+ = ABRE PARA LEER Y ESCRIBIR
#w+ = ABRE PARA LEER Y ESCRIBIR (PERO BORRA TODO LO QUE HAY EN EL ARCHIVO)
#a+ = ABRE PARA ESCRIBIR Y AGREGAR A LO QUE YA HABIA ESCRITO EN EL ARCHIVO

#LEER
text = animals.read() #PASA TODO EL TEXTO A LA VARIABLE
print(text)

#ESCRIBIR/AGREGAR
animals.write('\n') #AGREGA UNA LINEA VACIA PARA NO DEJAR EL NUEVO TEXTO PEGADO AL ANTERIOR
animals.write('elephant\n')
animals.write('frog\n')

#CERRAR
animals.close()